version: '3.8'

services:
  backend:
    build:
      context: ./app
    container_name: CKC-ships-backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./web-app
    container_name: CKC-ships-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge